# -*- coding: utf-8 -*-
"""db_ops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9jI67WqpOHRNLTUQrhhzUZEu1oPOHtU
"""

# db_ops.py
from datetime import datetime
from typing import Optional
import hashlib

from firebase_admin import firestore
from google.cloud import firestore as gcf
from Levenshtein import distance as lev

from settings import get_db
_db = get_db()

def uid_from_email(email: str) -> str:
    return hashlib.sha1((email or "anon@example.com").strip().lower().encode()).hexdigest()

def ensure_user_profile(uid: str, email: str):
    _db.collection("users").document(uid).set(
        {"email": email, "created_at": firestore.SERVER_TIMESTAMP}, merge=True
    )

def create_session(uid: str, resume_text: str, jd_text: str,
                   tone_pref: str="", length_pref: str="", highlights: str="",
                   model: str="llm", prompt_version: str="p1.0") -> str:
    ref = _db.collection("users").document(uid).collection("sessions").document()
    ref.set({
        "resume_raw": resume_text,
        "jd_raw": jd_text,
        "tone_pref": tone_pref,
        "length_pref": length_pref,
        "highlights": highlights,
        "model": model,
        "prompt_version": prompt_version,
        "created_at": datetime.utcnow(),
    })
    return ref.id

def save_letter(uid: str, session_id: str, text: str, kind: str):
    assert kind in ("draft","final")
    _db.collection("users").document(uid).collection("sessions").document(session_id) \
      .collection("letters").add({"type": kind, "text": text, "created_at": datetime.utcnow()})

def get_latest_draft(uid: str, session_id: str) -> Optional[str]:
    docs = _db.collection("users").document(uid).collection("sessions").document(session_id) \
        .collection("letters").where("type","==","draft") \
        .order_by("created_at", direction=gcf.Query.DESCENDING).limit(1).get()
    return docs[0].to_dict().get("text") if docs else None

def upsert_final_and_metric(uid: str, session_id: str, final_text: str) -> float:
    draft_text = get_latest_draft(uid, session_id) or ""
    d = float(lev(draft_text, final_text or ""))

    # single latest-final doc
    _db.collection("users").document(uid).collection("sessions").document(session_id) \
      .collection("letters").document("latest_final").set({
        "type": "final",
        "text": final_text or "",
        "created_at": datetime.utcnow()
      })

    # metric trail
    _db.collection("users").document(uid).collection("sessions").document(session_id) \
      .collection("metrics").add({
        "name": "edit_distance", "value": d, "created_at": datetime.utcnow()
      })
    return d

def save_feedback(uid: str, session_id: str, thumb: int, reason: str=""):
    _db.collection("users").document(uid).collection("sessions").document(session_id) \
      .collection("feedback").add({"thumb": int(thumb), "reason": reason, "created_at": datetime.utcnow()})

def promote_exemplar(uid: str, final_text: str):
    _db.collection("users").document(uid).collection("exemplars").add({
        "text": final_text or "", "approved_at": datetime.utcnow()
    })
