# -*- coding: utf-8 -*-
"""prompts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jtil55wJ1XegMHPninAiEZCmBTpmN7aI
"""

BASE_PROMPT = """You are a helpful assistant that writes tailored application letters.

Write a {length_style} {format_style} for the following job, emphasizing: {highlights}.

Tone: professional, concise, positive.

Output starts with a friendly hello. Output needs to be factual based on the person's resume.

=== RESUME ===
{resume}

=== JOB DESCRIPTION ===
{jd}
"""