# -*- coding: utf-8 -*-
"""settings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tz4vb0lmKEGIcMT_PcJsc89jaI9kRMXP
"""

# settings.py
import os
import firebase_init  # ensures Firebase Admin is initialized
from dotenv import load_dotenv
load_dotenv()  # harmless on Cloud Run

PROJECT_ID = "genie-hi-front"#os.getenv("FIREBASE_PROJECT_ID", "")
GOOGLE_APPLICATION_CREDENTIALS = "service-account-genie-hi-front.json"#os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

# LLM provider — default to Vertex (you don’t have openai in requirements)
LLM_PROVIDER = (os.getenv("LLM_PROVIDER") or "VERTEX").upper()
VERTEX_REGION = os.getenv("VERTEX_REGION", "us-central1")
VERTEX_MODEL  = os.getenv("VERTEX_MODEL", "gemini-2.5-flash")

import firebase_admin
from firebase_admin import credentials, firestore

def get_db():
    if not firebase_admin._apps:
        if GOOGLE_APPLICATION_CREDENTIALS and os.path.exists(GOOGLE_APPLICATION_CREDENTIALS):
            cred = credentials.Certificate(GOOGLE_APPLICATION_CREDENTIALS)
            firebase_admin.initialize_app(cred, {"projectId": PROJECT_ID} if PROJECT_ID else None)
        else:
            # Cloud Run uses Application Default Credentials automatically
            firebase_admin.initialize_app()
    return firestore.client()

